# Generated by Django 5.0.6 on 2024-06-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0008_socalmedia_delete_socal_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='socalmedia',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
    ]
